modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/XoleKo/TerraCraft-1.15.2/issues"
logoFile="logo.png"

[[mods]]
modId="terracraft"
version="1.0"
displayName="TerraCraft"
updateJSONURL="https://raw.githubusercontent.com/XoleKo/TerraCraft-1.15.2/1.15/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/terracraft"
authors="XoleKo"
description='''
WIP
'''

[[dependencies.terracraft]]
modId="minecraft"
mandatory=true
versionRange="[1.15.2]"
ordering="NONE"
side="BOTH"

[[dependencies.terracraft]]
modId="forge"
mandatory=true
versionRange="[31,)"
ordering="NONE"
side="BOTH"

[[dependencies.terracraft]]
modId="patchouli"
mandatory=false
ordering="NONE"
side="BOTH"